CC=cc
CFLAGS=-Wall -Wextra -Werror -gdwarf-4
NAME=libft.a
SRCS=ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c \
	 ft_isascii.c ft_isdigit.c ft_isprint.c ft_memchr.c ft_memcmp.c \
	 ft_memcpy.c ft_memmove.c ft_memset.c ft_strchr.c ft_strdup.c \
	 ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_strncmp.c ft_strnstr.c \
	 ft_strrchr.c ft_tolower.c ft_toupper.c ft_substr.c ft_strstr.c \
	 ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_striteri.c \
	 ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c
SRCB=ft_lstnew.c ft_lstadd_front.c ft_lstsize.c \
	 ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c \
	 ft_lstclear.c ft_lstiter.c ft_lstmap.c
HEADER=libft.h
OBJS=$(SRCS:.c=.o)
OBJB=$(SRCB:.c=.o)

$(NAME): $(OBJS)
	ar rcs $(NAME) $(OBJS)

%.o: %.c $(HEADER)
	$(CC) $(CFLAGS) $< -c -o $@

all: $(NAME)

re: fclean all

fclean: clean
	rm -rf $(NAME)

clean:
	rm -rf *.o

bonus: $(OBJS) $(OBJB)
	ar rcs $(NAME) $(OBJS) $(OBJB)

.PHONY: all clean fclean re bonus